// place files you want to import through the `$lib` alias in this folder.
export { default as "aquarium disco" } from "$lib/assets/videos/aquarium disco.mp4"
export { default as "attention seeker" } from "$lib/assets/videos/attention seeker.mp4"
export { default as "car wash" } from "$lib/assets/videos/car wash.mp4"
export { default as "cherish it while it lasts" } from "$lib/assets/videos/cherish it while it lasts.mp4"
export { default as "civil engineering" } from "$lib/assets/videos/civil engineering.mp4"
export { default as "constructive debate" } from "$lib/assets/videos/constructive debate.mp4"
export { default as "consult the mirror" } from "$lib/assets/videos/consult the mirror.mp4"
export { default as "pelican instincts" } from "$lib/assets/videos/pelican instincts.mp4"
export { default as "departure" } from "$lib/assets/videos/departure.mp4"
export { default as "drunk rhythm" } from "$lib/assets/videos/drunk rhythm.mp4"
export { default as "get a real job" } from "$lib/assets/videos/get a real job.mp4"
export { default as "heaven said no" } from "$lib/assets/videos/heaven said no.mp4"
export { default as "ikea solar system" } from "$lib/assets/videos/ikea solar system.mp4"
export { default as "in my thoughts again" } from "$lib/assets/videos/in my thoughts again.mp4"
export { default as "just a peek" } from "$lib/assets/videos/just a peek.mp4"
export { default as "just hanging out" } from "$lib/assets/videos/just hanging out.mp4"
export { default as "nice fade, dude" } from "$lib/assets/videos/nice fade, dude.mp4"
export { default as "office work" } from "$lib/assets/videos/office work.mp4"
export { default as "outer space" } from "$lib/assets/videos/outer space.mp4"
export { default as "public transit" } from "$lib/assets/videos/public transit.mp4"
export { default as "radiate" } from "$lib/assets/videos/radiate.mp4"
export { default as "ready for takeoff" } from "$lib/assets/videos/ready for takeoff.mp4"
export { default as "right on time" } from "$lib/assets/videos/right on time.mp4"
export { default as "Sisyphus" } from "$lib/assets/videos/Sisyphus.mp4"
export { default as "steady-state" } from "$lib/assets/videos/steady-state.mp4"
export { default as "superfund waterpark" } from "$lib/assets/videos/superfund waterpark.mp4"
export { default as "taking the dog for a walk" } from "$lib/assets/videos/taking the dog for a walk.mp4"
export { default as "the allure of freedom" } from "$lib/assets/videos/the allure of freedom.mp4"
export { default as "tickle me" } from "$lib/assets/videos/tickle me.mp4"
export { default as "what shampoo do you use" } from "$lib/assets/videos/what shampoo do you use.mp4"