// place files you want to import through the `$lib` alias in this folder.
export { default as "aquarium disco" } from "$lib/assets/videos/aquarium disco.webm"
export { default as "attention seeker" } from "$lib/assets/videos/attention seeker.webm"
export { default as "car wash" } from "$lib/assets/videos/car wash.webm"
export { default as "cherish it while it lasts" } from "$lib/assets/videos/cherish it while it lasts.webm"
export { default as "civil engineering" } from "$lib/assets/videos/civil engineering.webm"
export { default as "constructive debate" } from "$lib/assets/videos/constructive debate.webm"
export { default as "consult the mirror" } from "$lib/assets/videos/consult the mirror.webm"
export { default as "pelican instincts" } from "$lib/assets/videos/pelican instincts.webm"
export { default as "departure" } from "$lib/assets/videos/departure.webm"
export { default as "drunk rhythm" } from "$lib/assets/videos/drunk rhythm.webm"
export { default as "get a real job" } from "$lib/assets/videos/get a real job.webm"
export { default as "heaven said no" } from "$lib/assets/videos/heaven said no.webm"
export { default as "ikea solar system" } from "$lib/assets/videos/ikea solar system.webm"
export { default as "in my thoughts again" } from "$lib/assets/videos/in my thoughts again.webm"
export { default as "just a peek" } from "$lib/assets/videos/just a peek.webm"
export { default as "just hanging out" } from "$lib/assets/videos/just hanging out.webm"
export { default as "nice fade, dude" } from "$lib/assets/videos/nice fade, dude.webm"
export { default as "office work" } from "$lib/assets/videos/office work.webm"
export { default as "outer space" } from "$lib/assets/videos/outer space.webm"
export { default as "public transit" } from "$lib/assets/videos/public transit.webm"
export { default as "radiate" } from "$lib/assets/videos/radiate.webm"
export { default as "ready for takeoff" } from "$lib/assets/videos/ready for takeoff.webm"
export { default as "right on time" } from "$lib/assets/videos/right on time.webm"
export { default as "Sisyphus" } from "$lib/assets/videos/Sisyphus.webm"
export { default as "steady-state" } from "$lib/assets/videos/steady-state.webm"
export { default as "superfund waterpark" } from "$lib/assets/videos/superfund waterpark.webm"
export { default as "taking the dog for a walk" } from "$lib/assets/videos/taking the dog for a walk.webm"
export { default as "the allure of freedom" } from "$lib/assets/videos/the allure of freedom.webm"
export { default as "tickle me" } from "$lib/assets/videos/tickle me.webm"
export { default as "what shampoo do you use" } from "$lib/assets/videos/what shampoo do you use.webm"